version: '3.8'
services:
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx/conf.d:/etc/nginx/conf.d

  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80    

  postgres:
    image: postgres:13.3
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  redis:
    image: redis:6.2.4
    container_name: lde.redis
    ports:
      - 6380:6379
